version: 0.1.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- pwsh: dotnet pack ./sources/Eshva.DockerCompose/Eshva.DockerCompose.csproj
deploy:
- provider: NuGet
  api_key:
    secure: RwdsEIjhYDeJvFbfTZayjLHBWtVTmvwBwfKIiGWG+K7edtQ94Hd5lOuN9yvhG7oF
  skip_symbols: false